# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-FEAR-Log
version:      0.02
version_from: lib/Games/FEAR/Log.pm
installdirs:  site
requires:
    DBI:                           1.5
    File::Copy:                    0
    File::Temp:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
